// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// us_echo //
// ------- //

#define us_echo_wrap_target 0
#define us_echo_wrap 6

static const uint16_t us_echo_program_instructions[] = {
            //     .wrap_target
    0x20a0, //  0: wait   1 pin, 0                   
    0xa02b, //  1: mov    x, !null                   
    0x0044, //  2: jmp    x--, 4                     
    0x0005, //  3: jmp    5                          
    0x00c2, //  4: jmp    pin, 2                     
    0xa0c9, //  5: mov    isr, !x                    
    0x8000, //  6: push   noblock                    
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program us_echo_program = {
    .instructions = us_echo_program_instructions,
    .length = 7,
    .origin = -1,
};

static inline pio_sm_config us_echo_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + us_echo_wrap_target, offset + us_echo_wrap);
    return c;
}
#endif

